### ISSUE TITLE
No module named 'datawig.utils'; 'datawig' is not a package

### ISSUE THREAD

**Issue by CLWcynthia** [awslabs/datawig#109]
I tried to run the simpleimputer on pycharm, but reported an error, which surprisingly worked fine on the command line。

`Traceback (most recent call last):
  File "F:/pyfile/missing_data/datawig.py", line 9, in <module>
    import datawig.utils
  File "F:\pyfile\missing_data\datawig.py", line 9, in <module>
    import datawig.utils
ModuleNotFoundError: No module named 'datawig.utils'; 'datawig' is not a package`

**Comment by felixbiessmann** [comment]
Apologies for the late reply, but this doesn't sound like a datawig problem - can you check whether this is a problem with pycharm not using the same python version as you did in your command line setting?
