### ISSUE TITLE
Interpreting and loading outputs of datawig which are in module

### ISSUE THREAD

**Issue by bharath7896** [awslabs/datawig#112]
I have imputed a column using datawig but its returning output in the columns is an object which is <datawig.simple_imputer.SimpleImputer object at 0x7f5e05b40630> how can we further process and determine the value of this categorical datapoint it is even not saved in pickle file and is to be run again and again when restarteed kernel

**Comment by felixbiessmann** [comment]
can you share some code showing how you did the imputation?
