### ISSUE TITLE
Segment 11 warning

### ISSUE THREAD

**Issue by shoraj** [awslabs/datawig#117]
Unable to run datawig code in google colab

**Comment by felixbiessmann** [comment]
Could you provide any hints on what errors you got?

**Comment by shoraj** [comment]
Whenever I am trying to run the "import datawig" command the google collab
session is crashing and restarting. I tried to check the log it showed me a
warning which says Segmentation fault: 11 and  [bt] (0)
/usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x3c27360)
[0x7f813614c360] .



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
03/13/20,
04:38:10 PM

**Comment by felixbiessmann** [comment]
Hm, not sure to what extent this is a datawig issue, also we never have tested this in colab, but we'll look into it asap (probably after the ICML review deadline next week).

**Comment by shoraj** [comment]
Thank You.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
03/13/20,
04:47:05 PM

**Comment by felixbiessmann** [comment]
so it seems to be a backwards incompatibility issue with mxnet, picking a random older version seems to work. the below example just ran through in a colab notebook:

```python
!pip install mxnet==1.3.0
!pip install datawig

import datawig, numpy

# generate some data with simple nonlinear dependency
df = datawig.utils.generate_df_numeric() 
# mask 10% of the values
df_with_missing = df.mask(numpy.random.rand(*df.shape) > .9)

# impute missing values
df_with_missing_imputed = datawig.SimpleImputer.complete(df_with_missing)

df_with_missing_imputed
```

We'll fix the mxnet version number in the next release, sorry about that.

**Comment by shoraj** [comment]
Don't be sorry, actually, I had tried running datawig a few days ago, it
was absolutely fine. only from yesterday, I am facing the problem. All the
best, thank you for your immediate reply.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
03/13/20,
04:52:12 PM

**Comment by felixbiessmann** [comment]
Should be solved with [latest release](https://pypi.org/project/datawig/), please reopen if problem persists
