### ISSUE TITLE
Model optimization

### ISSUE THREAD

**Issue by CLWcynthia** [awslabs/datawig#119]
If I want to add attention mechanisms to optimize the model, Where should I operate？

**Comment by felixbiessmann** [comment]
Sorry for the late reply, the best place for this would probably be in a [``Featurizer``](https://github.com/awslabs/datawig/blob/master/datawig/mxnet_input_symbols.py#L28) subclass - but I'm not sure how easy that would be to integrate. 

Feel free to re-open this in case you need more help on this one.
