### ISSUE TITLE
Dependencies clashing

### ISSUE THREAD

**Issue by VKEERTHIVIKRAM** [awslabs/datawig#121]
numpy==1.18.0
scikit-learn[alldeps]==0.22.1
typing==3.6.6
pandas==0.25.0
mxnet==1.4.0
these are the requirements however mxnet 1.4.0 has numpy dependency as 1.14.6
and latest version of mxnet 1.6.0 has numpy dependencies 1.16.6.
As a result unable to install this package

**Comment by felixbiessmann** [comment]
have you tried installing and running it?

**Comment by VKEERTHIVIKRAM** [comment]
I am unable to install it gives the following error.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Admin\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-suvz3ulx\\datawig\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-suvz3ulx\\datawig\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Admin\AppData\Local\Temp\pip-install-suvz3ulx\datawig\pip-egg-info'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-suvz3ulx\datawig\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Admin\AppData\Local\Temp\pip-install-suvz3ulx\datawig\setup.py", line 6, in <module>
        with open(os.path.join(ROOT,"requirements","requirements.txt")) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-suvz3ulx\\datawig\\requirements\\requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by TammoR** [comment]
Working on a proper fix but before that you could install from source

```
git clone https://github.com/awslabs/datawig
cd datawig
```

Make this change to the requirements.txt
https://github.com/awslabs/datawig/pull/122/files

```
pip install .
```

**Comment by VKEERTHIVIKRAM** [comment]
Thanks
