### ISSUE TITLE
Feature request: Progress indicator

### ISSUE THREAD

**Issue by gautambak** [awslabs/datawig#128]
Howdy,

I'm playing around with datawig and it's really neat. I am using it for a fairly large file and it completed after almost 8 hours last night - it would be awesome if there was some indicator of progress.

Right now I'm checking my computer here and there to see if the CPU is maxed out and if the job is running. Tensorflow has a great progress bar that might be nice to help people estimate timing for large jobs.

**Comment by felixbiessmann** [comment]
Thanks a lot for the feedback, we just discussed this and we are thinking of including this in the next major release. 

For now, we would recommend to change the level of the logging functionality to keep track of the training status. 

Feel free to reopen this in case this wasn't helpful.
