### ISSUE TITLE
SimpleImputer.complete fails when output_path is not the default, i.e. not "."

### ISSUE THREAD

**Issue by angeliney** [awslabs/datawig#129]
`shutil.rmtree(output_col)` in `SimpleImputer.complete` fails because the directories are generated within the `output_path`. The code should have been `shutil.rmtree(os.path.join(output_path, output_col))`

**Comment by felixbiessmann** [comment]
Thanks a lot for catching this! We'll look into this asap, but in case you're faster with wrapping this in a pull request, we'd be happy to just approve it.

**Comment by angeliney** [comment]
Great, thank you for the quick response! Made a pull request here: https://github.com/awslabs/datawig/pull/130

**Comment by tdhd** [comment]
Closing issue as https://github.com/awslabs/datawig/pull/135 is merged now.
