### ISSUE TITLE
replace instead of creating new column

### ISSUE THREAD

**Issue by gautambak** [awslabs/datawig#132]
Hi There,

I'm wondering if it's possible to have datawig replace a existing column instead of creating a new column? 

For example, when I run df = imputer.predict(df). It takes the column I wanted to predict and adds a copy of _imputed and _imputed_proba.  

How can I avoid that and just replace the df's column with the new value?

**Comment by gautambak** [comment]
heads up, you can obviously merge the results once you review the probability which is cool but I suspect there are many people who just want their dataframe inputted like other tools operate.

**Comment by felixbiessmann** [comment]
Thanks for the suggestion, indeed this is a frequent use case and initially we had it designed like your suggesting. We then decided for the current design to avoid the risk of accidentally overwriting data.

We might introduce an ``inplace`` option in future releases though.

**Comment by gautambak** [comment]
that sounds good! Thank you. by the way, datawig is really cool. Thanks for all you and teams work.
