### ISSUE TITLE
WinError32 similar to #127

### ISSUE THREAD

**Issue by Vlado42** [awslabs/datawig#134]
Hi, I am using Jupyter Notebook(through Anaconda) and the SimpleImputer.complete. I am running Anaconda as an administrator. 

The error arises at shutil.rmtree(output_col), and the stack trace eventually calls os.unlink(fullname) in _rmtree_unsafe. 

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'SOME_PATH\\\\imputer.log'

I am unable to delete the imputer.log manually until I restart the notebook after which this is possible.

**Comment by felixbiessmann** [comment]
We just [released the latest version](https://pypi.org/project/datawig/0.2.0/) which should take care of these problems, hence I'm closing this, feel free to reopen if the problem persists.
