### ISSUE TITLE
Issue with explain method

### ISSUE THREAD

**Issue by 5agado** [awslabs/datawig#142]
I trained an Imputer model with a mix of categorical, numerical and bow encoder (and associated featurizers), but when I run the `explain` method on it I get this error:

```
~/opt/anaconda3/envs/extract/lib/python3.6/site-packages/datawig/imputer.py in explain(self, label, k, label_column)
    390         # for each data encoder extract (token_idx, token_idx_correlation_with_label), extract and apply idx2token map.
    391         feature_dict = dict(explained_label = label)
--> 392         for encoder, pattern in self.__class_patterns:
    393             # extract idx2token mappings
    394             if isinstance(encoder, CategoricalEncoder):

TypeError: 'NoneType' object is not iterable
```

I tried with a dummy setup and `explain` works, so I would like to know if you have any clue about what is exactly causing this in my more complex model

**Comment by felixbiessmann** [comment]
How did you train the imputer? If you used the SimpleImputer, make sure you set the [`is_explainable` flag in the constructor](https://github.com/awslabs/datawig/blob/master/datawig/simple_imputer.py#L95), if you're using the Imputer, that flag is [set automatically, depending on the featurizers provided](https://github.com/awslabs/datawig/blob/master/datawig/imputer.py#L93).

**Comment by 5agado** [comment]
I used the full Imputer, and was expecting to get explanation for all the input categorical columns

**Comment by felixbiessmann** [comment]
we only used a [very simple explanation method](https://pubmed.ncbi.nlm.nih.gov/24239590/) (which in our experience works better than other methods, including LIME, see some of our experiments [here](https://arxiv.org/abs/1901.08558)), for the Imputer it only works with [``works for Categorical and Tfidf inputs with a single categorical output column``](https://github.com/awslabs/datawig/blob/master/datawig/imputer.py#L92). 

What works well in most cases I've encountered is to concatenate all categorical and text columns (maybe with prefixes specific to each column) into one text column and use SimpleImputer with char-ngrams. 

Closing this for now, feel free to reopen if the explanation does not work with the encoders it should work with.
