### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by ivandubar** [awslabs/datawig#146]
I confirmed that I have the required dependency versions. 
scikit-learn[alldeps]==0.22.1
typing==3.6.6
pandas==0.25.3
mxnet==1.4.0

I successfully installed Datawig and the [quickstart example](https://github.com/awslabs/datawig#quickstart-example) works just fine. 

`import pandas as pd 
import datawig 
import numpy as np

df1 = datawig.utils.generate_df_numeric() 

df1_with_missing = df1.mask(np.random.rand(*df1.shape) > .9)

df1_with_missing_imputed = datawig.SimpleImputer.complete(df1_with_missing)`

However, when I try to apply it to my dataset, I get the following error: 
`df = pd.read_csv(abundance_file_path)
df_with_missing = df
df_with_missing_imputed = datawig.SimpleImputer.complete(df_with_missing)

/Applications/anaconda3/envs/Python_3-7/lib/python3.7/site-packages/sklearn/utils/extmath.py:765: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/Applications/anaconda3/envs/Python_3-7/lib/python3.7/site-packages/sklearn/utils/extmath.py:706: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)
Traceback (most recent call last):

  File "<ipython-input-18-107802b73afa>", line 2, in <module>
    df_with_missing_imputed = datawig.SimpleImputer.complete(df_with_missing)

  File "/Applications/anaconda3/envs/Python_3-7/lib/python3.7/site-packages/datawig/simple_imputer.py", line 527, in complete
    calibrate=False)

  File "/Applications/anaconda3/envs/Python_3-7/lib/python3.7/site-packages/datawig/simple_imputer.py", line 390, in fit
    calibrate=calibrate)

  File "/Applications/anaconda3/envs/Python_3-7/lib/python3.7/site-packages/datawig/imputer.py", line 263, in fit
    iter_train, iter_test = self.__build_iterators(train_df, test_df, test_split)

  File "/Applications/anaconda3/envs/Python_3-7/lib/python3.7/site-packages/datawig/imputer.py", line 604, in __build_iterators
    batch_size=self.batch_size

  File "/Applications/anaconda3/envs/Python_3-7/lib/python3.7/site-packages/datawig/iterators.py", line 231, in __init__
    self.start_padding_idx = int(data_frame.index.max() + 1)

ValueError: cannot convert float NaN to integer
`

**Comment by felixbiessmann** [comment]
Hm, can you check the content of your dataframe? It looks like ``data_frame.index.max()`` returns NaN, which is a bit suspicious?

**Comment by ivandubar** [comment]
df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Columns: 5745 entries, Species to candidate division.15
dtypes: float64(5457), int64(287), object(1)
memory usage: 897.8+ KB

df.index.max()
Out[7]: 19

I could send you by email some of the data.

**Comment by felixbiessmann** [comment]
You are trying to train a machine learning model with less than 19 data points (DataWig internally splits off some validation/test data). This will not work. I'd recommend to get at least two orders of magnitude more data and try it again.
