### ISSUE TITLE
imputer.predict should not modify dataframe in place.

### ISSUE THREAD

**Issue by TammoR** [awslabs/datawig#18]
As the title, says. When calling `imputer.predict(df)`, columns are appended to `df` such that a second call of the command throws an error.
This makes it unnecessarily complicated to apply different imputers to the same dataset, e.g. for comparing predictions.
Changing this may break backwards compatibility though.

**Comment by felixbiessmann** [comment]
good idea, that's easier to use. 
with large dfs that could create problems with memory requirements though, right? 

the current version was meant to have the same behaviour as the spark version, which just appended a column to an existing data frame. i think i had collected feedback at some point and the consensus was to have that behaviour and throw an error.

**Comment by andrey-tpt** [comment]
Ideally, it should be possible to give caller control over desired behavior by passing a flag to imputer:
 * if the flag is not set or set to 'False' - old behavior is assumed.
 * however if the flag is set to 'True' then new dataframe with imputed values is returned.
