### ISSUE TITLE
Improved logging levels

### ISSUE THREAD

**Issue by TammoR** [awslabs/datawig#27]
I would be nice to have a logging level, that is less verbose than _info_ but provide some basic information. _Info_ prints a line at every training batch. A useful logger could generate a statement at every epoch, or every n epochs and include:

- log-likelihood (train/test)
- number of epochs passed
- time passed
- time that the encoder took (which can be the bottleneck).

**Comment by TammoR** [comment]
Not sure how to best proceed with this, since the extremely verbose info logging is actually part of mxnet.

**Comment by andrey-tpt** [comment]
@TammoR It appears that MXNet uses standard *logging* module. Did you try to follow examples where logging levels are customized [1] ? Alternatively, they mostly use root logger from *logging* so it should be possible to customize it on our side. Now, if you want to reduce logging  in C++ backend then it's a different story and probably needs a PR to MXNet team.  

[1] https://github.com/apache/incubator-mxnet/blob/225f71f744ac5e7bd29868b6d3ba0e4fe2527c43/example/autoencoder/mnist_sae.py#L49

**Comment by TammoR** [comment]
Solved and merged: https://github.com/awslabs/datawig/pull/69
