### ISSUE TITLE
Return training metrics 

### ISSUE THREAD

**Issue by TammoR** [awslabs/datawig#57]
At the moment all metrics we evaluate automatically are measured wrt to the test data (except for the log likelihood). To analyse model performance in particular bias/variance, training accuracy is crucial.
We should add this.

The whole metrics computation, however, is cluttered and complicated and I wonder whether we should revisit it more fundamentally.

**Comment by felixbiessmann** [comment]
I also thought we should refactor some of the training metrics (the
cross-entropy and the accuracy).

I don't feel it's cluttered, it's all in one file, right? Only the training
metrics are not, we could move them to the evaluation module. But then
again it's mxnet stuff, which doesn't support many of the metrics we're
interested in. So it's ok to have it separate.

My reason for refactoring it was that currently, we print "cross-entropy"
and accuracy for both classfication and regression losses. It would be
great to have correct log statements, i.e. print MSE or something like that
for regression.

The follow up problem is that the API currently allows to have multiple
output columns. Categorical losses are then aggregated over multiple output
symbols.

When we allow for combinations of categorical and regression losses, it is
not clear however how these should be combined and weighted.

I'd rather not reduce the functionality, but if we're to clean up the
metrics, we should either
- fix the wrong log training label for regression losses and then think
about how to combine classification and regression losses (if we feel that
makes sense)
- fix the wrong log training label and get rid of multiple output symbols

What do you think?
