### ISSUE TITLE
AttributeError: module 'mxnet' has no attribute 'random'

### ISSUE THREAD

**Issue by imadeit** [awslabs/datawig#95]
Thanks for sharing amazing project.
I tried to run the first example provided in the README, by calling `import datawig` I just get errors.
--------
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-837b1662d604> in <module>
----> 1 import datawig
      2 
      3 df = datawig.utils.generate_df_string(num_samples=200, data_column_name='sentences', label_column_name='label')
      4 df_train, df_test = datawig.utils.random_split(df)
      5 

~/Development/repos/AWS/MBA/datawig/datawig/__init__.py in <module>
      1 # makes the column encoders available as e.g. `from datawig import CategoricalEncoder`
----> 2 from .column_encoders import CategoricalEncoder, BowEncoder, NumericalEncoder, SequentialEncoder
      3 from .mxnet_input_symbols import BowFeaturizer, LSTMFeaturizer, NumericalFeaturizer, EmbeddingFeaturizer
      4 from .simple_imputer import SimpleImputer
      5 from .imputer import Imputer

~/Development/repos/AWS/MBA/datawig/datawig/column_encoders.py in <module>
     30 from sklearn.preprocessing import StandardScaler
     31 
---> 32 from .utils import logger
     33 
     34 random.seed(0)

~/Development/repos/AWS/MBA/datawig/datawig/utils.py in <module>
     32 import pandas as pd
     33 
---> 34 mx.random.seed(1)
     35 random.seed(1)
     36 np.random.seed(42)

AttributeError: module 'mxnet' has no attribute 'random'
--------
Should I setup any conda env. for specific version of mxnet?

**Comment by felixbiessmann** [comment]
which mxnet version is that? 
was datawig installed with pip?
