### ISSUE TITLE
AttributeError: module 'mxnet' has no attribute 'random'

### ISSUE THREAD

**Issue by AeroClassics** [awslabs/datawig#97]
Build 1.4 today
Ubuntu 18.04
gcc-6, g++-6
Cuda 10
TensorRT
Tensorflow 1.13
Make option:
    USE_OPENCV=1 
    USE_BLAS=openblas 
    USE_CUDA=1 
    USE_CUDA_PATH=/usr/local/cuda 
    USE_CUDNN=1
    USE_NCCL=1
Compiled with only a warning about lapack
Copied the example into a python script and ran with python3

Error reported:
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    mx.random.seed(1234)
AttributeError: module 'mxnet' has no attribute 'random'

[test.zip](https://github.com/awslabs/datawig/files/2985103/test.zip)

**Comment by tdhd** [comment]
Which version of mxnet do you have installed?

**Comment by AeroClassics** [comment]
Hi Phillip,
1.4 is what I downloaded and built.

Best Regards / Mit freundlichen Grüßen,
Doug

[cid:image001.png@01D3D5F5.7EE2C150]

Douglas R. Jones
Sr. Software Engineer/AdVISE Architect.
Rohde & Schwarz USA, Inc.
1500 Lakeside Parkway Ste 100
Flower Mound, TX 75028
Mobile: +1 214-601-3301
Office: +1 469-713-5344
E-Mail: Doug.Jones@rsa.rohde-schwarz.com<mailto:Doug.Jones@rsa.rohde-schwarz.com>
Website: http://www.rohde-schwarz.com/

**Comment by tdhd** [comment]
I guess this has to do with how you have installed mxnet. I just did a clean install of mxnet 1.4 into a new conda environment and the module was found. How have you installed mxnet?

**Comment by AeroClassics** [comment]
I suppose I can believe that. I was following this [tutorial](https://www.pyimagesearch.com/2019/01/30/ubuntu-18-04-install-tensorflow-and-keras-for-deep-learning/). The main difference from the tutorial are:
OpenCV 3.4.5 (local build, rather than global)
Cuda 10
cuDNN for Cuda 10
TensorRT
Python 3.6
and I used one additional compiler flag USE_NCCL=1

I can try again and see what happens.

**Comment by AeroClassics** [comment]
Same error
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    mx.random.seed(1234)
AttributeError: module 'mxnet' has no attribute 'random'

I pulled a fresh copy using:
git clone --recursive https://github.com/apache/incubator-mxnet mxnet
cd mxnet
The I built it using:
make -j12 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 USE_NCCL=1 USE_NCCL_PATH=/usr/lib/x86_64-linux-gnu
cd ~/.virtualenvs/mxnet/lib/python3.6/site-packages/
ln -s ~/devel/software/mxnet mxnet
 Did a workon mxnet
and python3 test.py

So what could I have done incorrectly?

Thanks.

**Comment by felixbiessmann** [comment]
We fixed some issues with dependencies and tested the installation again. Following the instructions in the README should work, hence closing this issue, feel free to re-open if the problem persists.
